[package]
name = "citadel-desktopd"
version = "0.1.0"
authors = ["brl@subgraph.com"]

[dependencies]
failure = "0.1.1"
lazy_static = "1.0"
log = "0.4.0"
env_logger = "0.5.3"
inotify = "0.5"
toml = "0.4.5"
serde_derive = "1.0.27"
serde = "1.0.27"
nix = "0.10.0"
